# Generated by Django 5.0.4 on 2024-05-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название новостей  ')),
                ('description', models.TextField(verbose_name='Коментарии')),
            ],
            options={
                'verbose_name': 'Емаил',
                'verbose_name_plural': 'Емаил',
            },
        ),
    ]
