# Generated by Django 5.0.4 on 2024-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_subs_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название новостей'),
        ),
        migrations.AlterField(
            model_name='info_basket',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название новостей'),
        ),
    ]
