# Generated by Django 4.1.3 on 2022-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_oz', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('text_oz', models.TextField(null=True, verbose_name='Text')),
                ('text_uz', models.TextField(null=True, verbose_name='Text')),
                ('text_en', models.TextField(null=True, verbose_name='Text')),
                ('text_ru', models.TextField(null=True, verbose_name='Text')),
                ('count', models.IntegerField(default=0, null=True, verbose_name='count')),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
                ('image_extra1', models.ImageField(blank=True, upload_to='images', verbose_name='image')),
                ('image_extra2', models.ImageField(blank=True, upload_to='images', verbose_name='image')),
                ('image_extra3', models.ImageField(blank=True, upload_to='images', verbose_name='image')),
                ('image_extra4', models.ImageField(blank=True, upload_to='images', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
