# Generated by Django 4.1.3 on 2022-11-17 16:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_university', '0002_alter_introducemei_text_alter_legalinfo_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introducemei',
            options={'verbose_name': 'Introducing with MPEI', 'verbose_name_plural': 'Introducing with MPEI'},
        ),
        migrations.AddField(
            model_name='introducemei',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='introducemei',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='introducemei',
            name='text_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
