# Generated by Django 4.1.3 on 2022-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_university', '0004_alter_contact_options_alter_honorary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorary',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='image'),
        ),
    ]
