# Generated by Django 4.1.3 on 2022-11-27 11:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_university', '0005_alter_honorary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducemei',
            name='text_oz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text'),
        ),
    ]
