# Generated by Django 4.1.3 on 2022-12-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_university', '0006_introducemei_text_oz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
