# Generated by Django 4.1.3 on 2023-01-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_university', '0008_honorary_degree_en_honorary_degree_oz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QabulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qabullink', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Qabul link',
                'verbose_name_plural': 'Qabul link',
            },
        ),
    ]
