# Generated by Django 4.1.3 on 2022-11-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sayt logotipi (nom)')),
                ('logo_name_oz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sayt logotipi (nom)')),
                ('logo_name_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sayt logotipi (nom)')),
                ('logo_name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sayt logotipi (nom)')),
                ('logo_name_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sayt logotipi (nom)')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='static/assets/img', verbose_name='Sayt logotipi (rasm)')),
            ],
            options={
                'verbose_name': 'Site logo',
                'verbose_name_plural': 'Site logo',
            },
        ),
    ]
