# Generated by Django 4.1.3 on 2022-11-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_oz', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('some_text', models.TextField(null=True, verbose_name='Some text')),
                ('some_text_oz', models.TextField(null=True, verbose_name='Some text')),
                ('some_text_uz', models.TextField(null=True, verbose_name='Some text')),
                ('some_text_en', models.TextField(null=True, verbose_name='Some text')),
                ('some_text_ru', models.TextField(null=True, verbose_name='Some text')),
                ('image', models.ImageField(null=True, upload_to='images', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Introduction section',
                'verbose_name_plural': 'Introduction section',
            },
        ),
        migrations.AlterField(
            model_name='sitelogo',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Sayt logotipi (rasm)'),
        ),
    ]
