# Generated by Django 4.1.3 on 2022-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_introsection_alter_sitelogo_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram link')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook link')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube link')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter link')),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True, verbose_name='LinkedIn link')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram link')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp link')),
            ],
            options={
                'verbose_name': 'Social Links',
                'verbose_name_plural': 'Social Links',
            },
        ),
    ]
