# Generated by Django 4.1.3 on 2022-12-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_sociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='email')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='phone_number')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('address_oz', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('address_uz', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('address_URL', models.URLField(max_length=500, null=True, verbose_name='address URL')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
