# Generated by Django 4.1.3 on 2022-12-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_contactaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinOurNewsletterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Join our newsletter answers',
                'verbose_name_plural': 'Join our newsletter answers',
            },
        ),
        migrations.CreateModel(
            name='JoinOurNewsletterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('text_oz', models.TextField(null=True, verbose_name='Text')),
                ('text_uz', models.TextField(null=True, verbose_name='Text')),
                ('text_en', models.TextField(null=True, verbose_name='Text')),
                ('text_ru', models.TextField(null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Join our newsletter text',
                'verbose_name_plural': 'Join our newsletter text',
            },
        ),
    ]
