# Generated by Django 4.1.3 on 2022-12-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_receivedmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True, verbose_name='Fullname')),
                ('fullname_oz', models.CharField(max_length=100, null=True, verbose_name='Fullname')),
                ('fullname_uz', models.CharField(max_length=100, null=True, verbose_name='Fullname')),
                ('fullname_en', models.CharField(max_length=100, null=True, verbose_name='Fullname')),
                ('fullname_ru', models.CharField(max_length=100, null=True, verbose_name='Fullname')),
                ('profession', models.CharField(max_length=200, null=True, verbose_name='Profession')),
                ('profession_oz', models.CharField(max_length=200, null=True, verbose_name='Profession')),
                ('profession_uz', models.CharField(max_length=200, null=True, verbose_name='Profession')),
                ('profession_en', models.CharField(max_length=200, null=True, verbose_name='Profession')),
                ('profession_ru', models.CharField(max_length=200, null=True, verbose_name='Profession')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('text_oz', models.TextField(null=True, verbose_name='Text')),
                ('text_uz', models.TextField(null=True, verbose_name='Text')),
                ('text_en', models.TextField(null=True, verbose_name='Text')),
                ('text_ru', models.TextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(null=True, upload_to='images', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Testimonials',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
