# Generated by Django 4.1.3 on 2022-12-02 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_whychooseus_whychooseusreasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseusreasons',
            name='whychooseus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.whychooseus', verbose_name='whychooseus_id'),
        ),
    ]
