# Generated by Django 4.1.3 on 2022-12-02 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_whychooseusreasons_whychooseus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseusreasons',
            name='whychooseus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whychooseus', to='base.whychooseus', verbose_name='whychooseus_id'),
        ),
    ]
