# Generated by Django 4.1.3 on 2022-12-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_whychooseusreasons_whychooseus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedmessages',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone_number'),
        ),
    ]
