# Generated by Django 4.1.3 on 2022-12-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_introsection_title2_en_introsection_title2_oz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='introsection',
            name='video',
            field=models.FileField(null=True, upload_to='images', verbose_name='Video'),
        ),
    ]
