# Generated by Django 4.1.3 on 2022-12-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_introsection_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_oz', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_uz', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('answer', models.TextField(null=True, verbose_name='Answer')),
                ('answer_oz', models.TextField(null=True, verbose_name='Answer')),
                ('answer_uz', models.TextField(null=True, verbose_name='Answer')),
                ('answer_en', models.TextField(null=True, verbose_name='Answer')),
                ('answer_ru', models.TextField(null=True, verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'FAQs',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
