# Generated by Django 4.1.3 on 2023-06-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_mac_carusel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
            options={
                'verbose_name': 'видео каруселя',
                'verbose_name_plural': 'видео каруселей',
            },
        ),
    ]
