# Generated by Django 4.1.3 on 2022-11-28 13:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsAndCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Departments and centers of MPEI',
                'verbose_name_plural': 'Departments and centers of MPEI',
            },
        ),
        migrations.CreateModel(
            name='MPEIuzLeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_oz', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('academic_degree', models.CharField(max_length=200, verbose_name='Academic degree')),
                ('academic_degree_oz', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('academic_degree_uz', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('academic_degree_en', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('academic_degree_ru', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Heads of MPEI Tashkent branch',
                'verbose_name_plural': 'Heads of MPEI Tashkent branch',
            },
        ),
        migrations.CreateModel(
            name='OfficesAndDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Offices and departments of MPEI',
                'verbose_name_plural': 'Offices and departments of MPEI',
            },
        ),
        migrations.CreateModel(
            name='PublicOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Public organizations',
                'verbose_name_plural': 'Public organizations',
            },
        ),
        migrations.CreateModel(
            name='ScientificCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_oz', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('academic_degree', models.CharField(max_length=200, verbose_name='Academic degree')),
                ('academic_degree_oz', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('academic_degree_uz', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('academic_degree_en', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('academic_degree_ru', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Scientific Council',
                'verbose_name_plural': 'Scientific Council',
            },
        ),
        migrations.CreateModel(
            name='TheBoardOfDirectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_oz', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('academic_degree', models.CharField(max_length=200, verbose_name='Academic degree')),
                ('academic_degree_oz', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('academic_degree_uz', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('academic_degree_en', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('academic_degree_ru', models.CharField(max_length=200, null=True, verbose_name='Academic degree')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('position_oz', models.CharField(max_length=200, null=True, verbose_name='Position')),
                ('position_uz', models.CharField(max_length=200, null=True, verbose_name='Position')),
                ('position_en', models.CharField(max_length=200, null=True, verbose_name='Position')),
                ('position_ru', models.CharField(max_length=200, null=True, verbose_name='Position')),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'The board of directors',
                'verbose_name_plural': 'The board of directors',
            },
        ),
        migrations.CreateModel(
            name='UniversityManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'University management',
                'verbose_name_plural': 'University management',
            },
        ),
        migrations.CreateModel(
            name='MPEIuzLeaderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('MPEIuzLeaders_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='structure.mpeiuzleaders', verbose_name='Heads of MPEI Tashkent branch')),
            ],
            options={
                'verbose_name': 'Head detail of MPEI Tashkent branch',
                'verbose_name_plural': 'Head detail of MPEI Tashkent branch',
            },
        ),
    ]
