# Generated by Django 4.1.3 on 2022-12-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificcouncil',
            name='about',
            field=models.CharField(max_length=255, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='scientificcouncil',
            name='about_en',
            field=models.CharField(max_length=255, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='scientificcouncil',
            name='about_oz',
            field=models.CharField(max_length=255, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='scientificcouncil',
            name='about_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='scientificcouncil',
            name='about_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='About'),
        ),
    ]
