# Generated by Django 4.1.3 on 2022-12-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_mpeiuzleaders_some_text_mpeiuzleaders_some_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpeiuzleaders',
            name='email',
            field=models.CharField(max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='mpeiuzleaders',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone number'),
        ),
    ]
