# Generated by Django 4.1.3 on 2022-12-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_rename_mpeiuzleaders_id_mpeiuzleaderdetail_mpeiuzleaders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpeiuzleaderdetail',
            name='mpeiuzLeaders_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.mpeiuzleaders', verbose_name='Heads of MPEI Tashkent branch'),
        ),
    ]
