# Generated by Django 4.1.3 on 2022-11-28 13:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMPEIStudentsForeignPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Foreign Programs of Students of MPEI',
                'verbose_name_plural': 'Foreign Programs of Students of MPEI',
            },
        ),
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Cooperation',
                'verbose_name_plural': 'Cooperation',
            },
        ),
        migrations.CreateModel(
            name='ForeignPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_oz', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Foreign Programs',
                'verbose_name_plural': 'Foreign Programs',
            },
        ),
        migrations.CreateModel(
            name='GlobalEnergyAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Global Energy Association',
                'verbose_name_plural': 'Global Energy Association',
            },
        ),
        migrations.CreateModel(
            name='Graduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Graduates',
                'verbose_name_plural': 'Graduates',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Information',
            },
        ),
        migrations.CreateModel(
            name='OrganizationCIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'The main organization of the CIS',
                'verbose_name_plural': 'The main organization of the CIS',
            },
        ),
        migrations.CreateModel(
            name='PreparingForeigners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Preparing foreigners',
                'verbose_name_plural': 'Preparing foreigners',
            },
        ),
        migrations.CreateModel(
            name='RegistrationForAMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Registration form for participants of the 25th anniversary conference of AMO',
                'verbose_name_plural': 'Registration form for participants of the 25th anniversary conference of AMO',
            },
        ),
        migrations.CreateModel(
            name='ForeignProgramDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_oz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('foreignprograms_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign.foreignprograms')),
            ],
            options={
                'verbose_name': 'Foreign Program detail',
                'verbose_name_plural': 'Foreign Program detail',
            },
        ),
    ]
