# Generated by Django 4.1.3 on 2022-11-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science_and_innovation', '0002_eduprogram_text_en_eduprogram_text_ru_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EduProgram',
            new_name='ScientInfrastructure',
        ),
    ]
