# Generated by Django 4.1.3 on 2022-12-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_additionaledu_text_oz_distanceedu_text_oz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='education.group', verbose_name='Groups'),
        ),
    ]
