# Generated by Django 4.1 on 2024-03-26 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YookassaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('yookassa_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('recipient_account_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('recipient_gateway_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('yookassa_created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
