# Generated by Django 4.1 on 2024-03-27 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyclick', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yookassaorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yookassa_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClickOrder',
            fields=[
                ('clicktransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pyclick.clicktransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_order', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('pyclick.clicktransaction',),
        ),
    ]
