# Generated by Django 4.1.3 on 2022-12-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='ads',
            name='area_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='ads',
            name='area_oz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='ads',
            name='area_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='ads',
            name='area_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='ads',
            name='count',
            field=models.IntegerField(default=0, null=True, verbose_name='count'),
        ),
        migrations.AddField(
            model_name='ads',
            name='period',
            field=models.DateField(null=True, verbose_name='period'),
        ),
        migrations.AddField(
            model_name='ads',
            name='text',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='ads',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='ads',
            name='text_oz',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='ads',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='ads',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
